openapi: 3.0.1
info:
  title: PayCenterRTPAPI
  version: v1
servers:
 -
  url: /
security:
 -
  default: []
paths:
  /{rtnnumber}/environments/{envname}/products/paycenter/networks/rtp/refund-requests:
    post:
      parameters:
       -
        name: rtnnumber
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
       -
        name: envname
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        200:
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  /{rtnnumber}/environments/{envname}/products/paycenter/networks/rtp/credit-transfers:
    post:
      parameters:
       -
        name: rtnnumber
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
       -
        name: envname
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        200:
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  /{rtnnumber}/environments/{envname}/products/paycenter/networks/rtp/payment-requests:
    post:
      parameters:
       -
        name: rtnnumber
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
       -
        name: envname
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        200:
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://test.com
          scopes: {}
